apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testchatbot2-jul25 
  description: Secure Supply Chain Example for Chatbot Application example with LLM enabled chat applications   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=testchatbot2-jul25  
    janus-idp.io/tekton: testchatbot2-jul25 
    backstage.io/kubernetes-id: testchatbot2-jul25 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jctestorg/testchatbot2-jul25
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 